version: "3.9"
services:
  flaskapp:
    container_name: flaskweb
    build:
      context: .
    ports:
      - "5001:5001"
    networks:
      hello_flask:
        aliases:
          - hello_123
  nginx:
    image: nginx:1.20.2
    volumes:
      - ./mynginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1234:80
    depends_on:
      - flaskapp
    networks:
      - hello_flask
networks:
  hello_flask: